categories:
- id: "app_sec"
  name: "Application Security"
  description: "Metrics related to application security posture"
  kpis:
    - id: "vuln_remediation_time"
      name: "Vulnerability Remediation Time"
      description: "Average time to remediate vulnerabilities"
      unit: "days"
      scoring_bands:
        - score: 95
          max: 15
        - score: 85
          min: 15
          max: 30
        - score: 75
          min: 30
          max: 45
        - score: 65
          min: 45
          max: 60
        - score: 30
          min: 60
  kris:
    - id: "critical_vulns"
      name: "Critical Vulnerabilities"
      description: "Number of critical vulnerabilities"
      unit: "count"
      scoring_bands:
        - score: 95
          max: 0
        - score: 85
          min: 0
          max: 2
        - score: 75
          min: 2
          max: 5
        - score: 65
          min: 5
          max: 10
        - score: 30
          min: 10