name: SBOM Generation and Vulnerability Scanning

on:
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate SBOM using Anchore Syft
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: sbom.json
          path: .

      # Scan the SBOM for vulnerabilities using Anchore Grype
      - name: Scan SBOM for vulnerabilities
        id: scan
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.json
          # Set fail-build to true to fail the workflow if critical vulnerabilities are found
          fail-build: false
          severity-cutoff: critical
          # Optional: Output the vulnerability report
          output-format: sarif
          only-fixed: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      # Archive the SBOM as an artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ./sbom.json
